name: Publish Utility.Result

on:
  push:
    branches: [ master ]
    paths:
      - 'Utility.Result/**'

  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Publish Package
        uses: Baboon-Co/utility/Actions/publish-nuget-package@master
        with:
          project_name: Utility.Result
          version-tag-name: utility-result