name: Publish Utility.Configuration

on:
  push:
    branches: [ master ]
    paths:
      - 'Utility.Configuration/**'

  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Publish Package
        uses: ./.github/actions/publish-nuget-package
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          project-name: Utility.Configuration
          version-tag-name: utility-configuration