name: Publish Utility.Grpc.Server

on:
  push:
    branches: [ master ]
    paths:
      - 'Utility.Grpc.Server/**'

  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Publish Package
        uses: Baboon-Co/utility/Actions/publish-nuget-package@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          project-name: Utility.Grpc.Server
          version-tag-name: utility-grpc-server